/* If these tokens need to change, don't forget to change the correspoding scss file */

/* All colours should use a token - these all match up with the designs */
export const Colours = {
  bg_primary: '--color-bg-primary',
  on_bg_primary_1: '--color-on-bg-primary-1',
  on_bg_primary_2: '--color-on-bg-primary-2',
  container_on_bg_primary: '--color-container-on-bg-primary',
  on_container_primary_1: '--color-on-container-primary-1',
  on_container_primary_2: '--color-on-container-primary-2',
  bg_secondary: '--color-bg-secondary',
  on_bg_secondary_1: '--color-on-bg-secondary-1',
  on_bg_secondary_2: '--color-on-bg-secondary-2',
  container_on_bg_secondary: '--color-container-on-bg-secondary',
  on_container_secondary_1: '--color-on-container-secondary-1',
  on_container_secondary_2: '--color-on-container-secondary-2',
  accent_1_primary: '--color-accent-1-primary',
  accent_1_shade: '--color-accent-1-shade',
  accent_1_small: '--color-accent-1-small',
  on_accent_1_primary: '--color-on-accent-1-primary',
  on_accent_1_small: '--color-on-accent-1-small',
  accent_2_primary: '--color-accent-2-primary',
  on_accent_2_small: '--color-on-accent-2-small',
  accent_3_primary: '--color-accent-3-primary',
  on_accent_3_small: '--color-on-accent-3-small',
  action_primary: '--color-action-primary',
  on_action_primary: '--color-on-action-primary',
  action_outline_primary: '--color-action-outline-primary',
  on_action_outline_primary: '--color-on-action-outline-primary',
  disabled_action_primary: '--color-disabled-action-primary',
  on_disabled_action_primary: '--color-on-disabled-action-primary',
  action_secondary: '--color-action-secondary',
  on_action_secondary: '--color-on-action-secondary',
  action_outline_secondary: '--color-action-outline-secondary',
  on_action_outline_secondary: '--color-on-action-outline-secondary',
  disabled_action_secondary: '--color-disabled-action-secondary',
  on_disabled_action_secondary: '--color-on-disabled-action-secondary',
  action_small: '--color-action-small',
  on_action_small: '--color-on-action-small',
  action_outline_small: '--color-action-outline-small',
  on_action_outline_small: '--color-on-action-outline-small',
  error: '--color-error',
  on_error: '--color-on-error',
  error_outline: '--color-error-outline',
  success: '--color-success',
  on_success: '--color-on-success',
  success_outline: '--color-success-outline',
  alert: '--color-alert',
  on_alert: '--color-on-alert',
  alert_outline: '--color-alert-outline',
};
